// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace monitoria_dotnet_webapi.Migrations
{
    [DbContext(typeof(ContextoBancoDeDados))]
    [Migration("20221029140919_MigracaoJogoGenero")]
    partial class MigracaoJogoGenero
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("int")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_tab_generos");

                    b.ToTable("tab_generos", (string)null);
                });

            modelBuilder.Entity("Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("criado_em");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("int")
                        .HasColumnName("criado_por");

                    b.Property<int>("FaixaEtaria")
                        .HasColumnType("int")
                        .HasColumnName("faixa_etaria");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int")
                        .HasColumnName("genero_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("titulo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PK_tab_jogos");

                    b.HasIndex("GeneroId");

                    b.ToTable("tab_jogos", (string)null);
                });

            modelBuilder.Entity("Jogo", b =>
                {
                    b.HasOne("Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });
#pragma warning restore 612, 618
        }
    }
}
