public enum Regiao {
  AMERICA_NORTE_LESTE,
  AMERICA_NORTE_OESTE,
  AMERICA_SUL,
  EUROPA_CENTRAL,
  EUROPA_OESTE,
  EURASIA,
  ASIA_PACIFICO,
  ASIA_INDICO,
  ASIA_CENTRAL,
  ORIENTE_MEDIO,
  AFRICA
}